// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetProcessInfoByPort(arg1) {
  return window['go']['main']['App']['GetProcessInfoByPort'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Kill(arg1) {
  return window['go']['main']['App']['Kill'](arg1);
}
